apiVersion: v1
kind: ServiceAccount
metadata:
  name: clo835
  namespace: final
  annotations:
    # We use LabRole because Learner Labs blocks creating new roles
    eks.amazonaws.com/role-arn: arn:aws:iam::533267189120:role/LabRole
